Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -32,3 +32,14 @@ jobs:
       run: |
         export DATABRICKS_HOST=https://dbc-6cad2402-4428.cloud.databricks.com
         databricks jobs run-now --job-id 62667569273248
+        
+        job_status=$(62667569273248 get ... | jq -r '.state')
+        
+        if [ "$job_status" == "SUCCESS" ]; then
+            echo "Databricks job ran successfully"
+            exit 0
+        else
+          echo "Databricks job failed"
+          exit 1
+          
+        fi
